"""
data_preprocessing.py
----------------------
Loading, cleaning and feature engineering for the Amazon product sales
dataset. Designed to accept EITHER:
  1) data/raw/amazon_products_sample.csv  (single file, generated by
     scripts/generate_sample_data.py), OR
  2) data/raw/amazon_categories/*.csv     (the real Kaggle per-category
     CSVs, if you've downloaded them -- same column layout, they get
     concatenated automatically, exactly like the original project's
     zipfile-merge step).
"""
from __future__ import annotations

import glob
import os
import re
from dataclasses import dataclass

import numpy as np
import pandas as pd

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "raw")
PROCESSED_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "processed")

RENAME_MAP = {"no_of_ratings": "total_sales", "name": "product_description"}
KEEP_COLS = ["product_description", "main_category", "sub_category",
             "ratings", "total_sales", "discount_price", "actual_price"]

PRICE_BANDS = [0, 500, 1500, 5000, 20000, np.inf]
PRICE_BAND_LABELS = ["Budget (<₹500)", "Value (₹500-1.5k)", "Mid (₹1.5k-5k)",
                      "Premium (₹5k-20k)", "Luxury (₹20k+)"]


def _clean_price(series: pd.Series) -> pd.Series:
    """Strip currency symbols/commas and coerce to float, matching the
    original notebook's `.str.replace('₹','').str.replace(',','')` step,
    but done safely with regex so it doesn't choke on already-numeric
    columns or stray whitespace."""
    return (
        series.astype(str)
        .str.replace(r"[^\d.]", "", regex=True)
        .replace("", np.nan)
        .astype(float)
    )


def load_raw() -> pd.DataFrame:
    """Load either the real per-category Kaggle CSVs (if present) or the
    bundled sample dataset. Mirrors the original project's zip-extraction
    + concat step (Chapter 6.1 of the original report)."""
    real_dir = os.path.join(RAW_DIR, "amazon_categories")
    real_files = glob.glob(os.path.join(real_dir, "*.csv"))

    if real_files:
        dfs = [pd.read_csv(f) for f in real_files]
        df = pd.concat(dfs, ignore_index=True)
        source = f"{len(real_files)} real Kaggle category files"
    else:
        sample_path = os.path.join(RAW_DIR, "amazon_products_sample.csv")
        if not os.path.exists(sample_path):
            raise FileNotFoundError(
                "No data found. Run `python scripts/generate_sample_data.py` "
                "first, or drop the real Kaggle per-category CSVs into "
                "data/raw/amazon_categories/."
            )
        df = pd.read_csv(sample_path)
        source = "bundled sample dataset"

    print(f"[data_preprocessing] Loaded {len(df):,} rows from {source}")
    return df


def clean_and_engineer(df: pd.DataFrame) -> pd.DataFrame:
    """Full cleaning + feature engineering pipeline. Returns a tidy
    dataframe with engineered business features ready for modeling and
    for the business-analytics exports."""
    df = df.copy()

    # Drop non-informative / leakage-free columns present in the raw export
    for col in ("Unnamed: 0", "image", "link"):
        if col in df.columns:
            df = df.drop(columns=col)

    df = df.rename(columns=RENAME_MAP)

    # Basic null / duplicate handling
    df = df.dropna(subset=["product_description", "main_category", "sub_category"])
    df = df.drop_duplicates()

    # Normalise category text
    df["main_category"] = df["main_category"].astype(str).str.strip().str.lower()
    df["sub_category"] = df["sub_category"].astype(str).str.strip().str.lower()

    # Prices -> numeric
    df["discount_price"] = _clean_price(df["discount_price"])
    df["actual_price"] = _clean_price(df["actual_price"])

    # Ratings / sales -> numeric
    df["ratings"] = pd.to_numeric(df["ratings"], errors="coerce")
    df["total_sales"] = pd.to_numeric(df["total_sales"], errors="coerce")

    # Drop rows where key numeric fields are unusable
    df = df.dropna(subset=["discount_price", "actual_price", "ratings", "total_sales"])
    df = df[(df["actual_price"] > 0) & (df["discount_price"] >= 0)]
    df = df[df["discount_price"] <= df["actual_price"] * 1.01]  # sanity guard

    # ---- Feature engineering (this is the "advanced feature engineering"
    # the original report promised in section 3.4 but never actually
    # implemented) --------------------------------------------------------
    df["discount_percentage"] = np.where(
        df["actual_price"] > 0,
        ((df["actual_price"] - df["discount_price"]) / df["actual_price"] * 100).round(2),
        0.0,
    )
    df["price_band"] = pd.cut(df["actual_price"], bins=PRICE_BANDS, labels=PRICE_BAND_LABELS)
    df["description_length"] = df["product_description"].str.len()
    df["description_word_count"] = df["product_description"].str.split().str.len()
    df["is_high_rated"] = (df["ratings"] >= 4.0).astype(int)
    df["estimated_revenue"] = df["discount_price"] * df["total_sales"]

    # Remove extreme outliers on the target using IQR (keeps the model honest;
    # the original project never did this and it likely contributed to the
    # nonsensical R2 = 1.58 reported in Chapter 9)
    q1, q3 = df["total_sales"].quantile([0.25, 0.75])
    iqr = q3 - q1
    upper = q3 + 3 * iqr
    df = df[df["total_sales"] <= max(upper, 50)]

    df = df.reset_index(drop=True)
    return df


def get_clean_dataset(save: bool = True) -> pd.DataFrame:
    raw = load_raw()
    clean = clean_and_engineer(raw)
    if save:
        os.makedirs(PROCESSED_DIR, exist_ok=True)
        out_path = os.path.join(PROCESSED_DIR, "clean_products.csv")
        clean.to_csv(out_path, index=False)
        print(f"[data_preprocessing] Saved cleaned dataset -> {out_path} ({len(clean):,} rows)")
    return clean


if __name__ == "__main__":
    df = get_clean_dataset()
    print(df.describe(include="all").T)
